### ISSUE TITLE
/tmp/if-you-need-to-delete-this-open-an-issue-async-disk-cache growing too large

### ISSUE THREAD

**Issue by kmiyashiro** [stefanpenner/async-disk-cache#54] opened 2017-04-13 19:19 UTC
We recently had to delete this folder because it had grown so large that one of our slugging machines ran out of disk space. All the machine does is install dependencies and runs `ember build`. Is there any way to ensure this does not happen?

**Comment by stefanpenner** [comment] 2017-04-13 21:15
@kmiyashiro `tmp` should be auto-cleaned by the OS typically. What OS/set do you have?

**Comment by kmiyashiro** [comment] 2017-04-14 18:08
@stefanpenner Amazon linux

**Comment by stefanpenner** [comment] 2017-04-14 18:33
This appears to be a duplicate of: https://github.com/stefanpenner/async-disk-cache/issues/35

My guess is that your linux doesn't have its tmp cleaner enable: http://manpages.ubuntu.com/manpages/wily/man8/tmpreaper.8.html is quite common for this.

---

Question, is this a CI box?

**Closed by stefanpenner** 2017-04-14 18:33 UTC

**Comment by kmiyashiro** [comment] 2017-04-14 20:48
Yes, it is a CI box.

**Comment by stefanpenner** [comment] 2017-04-14 21:15
We should likely disable the cache on CI boxes. Do you use `CI=true` environment variable?

**Comment by kmiyashiro** [comment] 2017-04-14 22:36
We might, we can easily add it or just use the DISABLE_DISK_CACHE
